### ISSUE TITLE
Predict.py output is silence

### ISSUE THREAD

**Issue by harshvardhan-truefan** [slp-rl/aero#14]
Hi, 
I have used the pre-trained checkpoint for 16-48. My original audio file is 16Khz. I want to perform super-res to enhance the quality of speech. I have replaced the checkpoint path in the main_config.yaml. But there is no audio in the output that I'm getting, it's just a silence audio. Any idea why that might be the case? 

Thanks in advance ! 

Regards,
Harsh

**Comment by m-mandel** [comment]
Hey Harsh,

Regarding the 16-48 checkpoint, I'm not sure - as I did not prepare this checkpoint. Maybe you can ask @fmac2000, who trained this configuration.

Can you try to downsample your signal to 12kHz, and use the 12-48 checkpoint?

Let me know your results.

Best,
M

**Comment by harshvardhan-truefan** [comment]
Hey @m-mandel ! Thank you for your quick response. Sure, I will try doing it. Thank you for your help ! :)

**Comment by fmac2000** [comment]
Hi @harshvardhan-truefan, the checkpoint was trained using VCTK, from what I found if you use a sample that is really out of domain, ie, something that isn't similar to VCTK - it will result in silence.

If you'd share with me the audio file I can test it on my end. I use this site often: https://vocaroo.com/upload
Thanks

**Comment by harshvardhan-truefan** [comment]
Hi @fmac2000, understood your point. I have uploaded the audio file on the following link. You can access the audio file from here. Please let me know if you face any issues for the same. 

https://voca.ro/16mXCSSYHc69

Regards,
Harsh

**Comment by fmac2000** [comment]
> Hi @fmac2000, understood your point. I have uploaded the audio file on the following link. You can access the audio file from here. Please let me know if you face any issues for the same.
> 
> [voca.ro/16mXCSSYHc69](https://voca.ro/16mXCSSYHc69)
> 
> Regards, Harsh

Hi Harsh, you are right - I must have incorrectly trained the model... Or perhaps the 16-48 model is overfit/underfit? I can replicate your issue on my end, when I use my own voice it works perfectly however. Downsampling to 12khz and using Mandel's model [works perfectly with your voice clip](https://vocaroo.com/12oe1W8HQoNq). 

Sorry to disappoint, I suggest you only use thick British accents for it to work! 😆

@m-mandel What would be the cause of this?

**Comment by harshvardhan-truefan** [comment]
Hi @fmac2000, 
That's okay, I think it might be a case of over-fitting... 
When you tried down sampling and using Mandel's model, did the output have the same voice as the input ? Can you share your output of the 12-48 model with the voice clip that I provided ? Because I tried down sampling to 12kHz and using the 12-48 model, but in the generated super-res output, the voice of the speaker changes to a man... is there a way to solve it ? 

Thanks for your quick response @fmac2000 ! :)

Regards,
Harsh

**Comment by fmac2000** [comment]
Ah well, if its borked i'll probably get around to retraining AERO again, with a more diverse dataset with a higher upsampling bound and stereo input/out - its such a fantastic paper. 

Huh weird, I've never come across a pitch change - perhaps there was an error with how you changed the samplerate? Check the link I put in the last comment, it's working fine on my end.

**Comment by harshvardhan-truefan** [comment]
Hey @fmac2000,
I was able to make it work after down sampling my audio to 12kHz. Thanks a lot for your help and quick response, really appreciate it. 

Regards,
Harsh

**Comment by youssefabdelm** [comment]
Hey @harshvardhan-truefan Would you be open to sharing code for getting it to work? I'm kinda struggling with all the config files and stuff, I just wanna run it and see what it's like

**Comment by youssefabdelm** [comment]
<img width="293" alt="Screenshot 2023-10-19 at 11 07 31 PM" src="https://github.com/slp-rl/aero/assets/74838919/ac762b1e-7ffa-4042-87ba-18b4ab3f235c">


My folder structure is like so

And my config is like so:
```
defaults:
  - experiment: aero-nfft=512-hl=64
  - dset: 16-48
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
```

And I'm getting this error:

```
/content/aero/predict.py:41: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="main_config")  # for latest version of hydra=1.0
/usr/local/lib/python3.10/dist-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'main_config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
In 'main_config': Could not find 'experiment/aero-nfft=512-hl=64'

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///content/aero/conf
	provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
	provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

**Comment by youssefabdelm** [comment]
Never mind! Figured it out eventually, although in Colab I'm getting this error now even though my file is only 8 seconds long:

```python
/content/aero/predict.py:41: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="main_config")  # for latest version of hydra=1.0
/usr/local/lib/python3.10/dist-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'main_config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
{'experiment': {'name': 'aero-nfft=${experiment.nfft}-hl=${experiment.hop_length}', 'lr_sr': 4000, 'hr_sr': 16000, 'segment': 2, 'stride': 2, 'pad': True, 'upsample': False, 'batch_size': 16, 'nfft': 512, 'hop_length': 64, 'model': 'aero', 'aero': {'in_channels': 1, 'out_channels': 1, 'channels': 48, 'growth': 2, 'nfft': '${experiment.nfft}', 'hop_length': '${experiment.hop_length}', 'end_iters': 0, 'cac': True, 'rewrite': True, 'hybrid': False, 'hybrid_old': False, 'freq_emb': 0.2, 'emb_scale': 10, 'emb_smooth': True, 'kernel_size': 8, 'strides': [4, 4, 2, 2], 'context': 1, 'context_enc': 0, 'freq_ends': 4, 'enc_freq_attn': 0, 'norm_starts': 2, 'norm_groups': 4, 'dconv_mode': 1, 'dconv_depth': 2, 'dconv_comp': 4, 'dconv_time_attn': 2, 'dconv_lstm': 2, 'dconv_init': 0.001, 'rescale': 0.1, 'lr_sr': '${experiment.lr_sr}', 'hr_sr': '${experiment.hr_sr}', 'spec_upsample': True, 'act_func': 'snake', 'debug': False}, 'adversarial': True, 'features_loss_lambda': 100, 'only_features_loss': False, 'only_adversarial_loss': False, 'discriminator_models': ['msd_melgan'], 'melgan_discriminator': {'n_layers': 4, 'num_D': 3, 'downsampling_factor': 4, 'ndf': 16}}, 'dset': {'name': '16-48', 'train': 'egs/vctk/16-48/tr', 'valid': None, 'test': 'egs/vctk/16-48/val'}, 'num_prints': 5, 'device': 'cuda', 'num_workers': 2, 'verbose': 0, 'show': 0, 'log_results': True, 'checkpoint': True, 'continue_from': '', 'continue_best': False, 'restart': False, 'checkpoint_file': '/content/aero/conf/aero-nfft=512-hl=64/checkpoint.th', 'best_file': 'best.th', 'history_file': 'history.json', 'test_results_file': 'test_results.json', 'samples_dir': 'samples', 'keep_history': True, 'seed': 2036, 'dummy': '', 'visqol': True, 'visqol_path': None, 'eval_every': 25, 'enhance_samples_limit': -1, 'valid_equals_test': None, 'cross_valid': False, 'cross_valid_every': 5, 'joint_evaluate_and_enhance': True, 'evaluate_on_best': False, 'wandb': {'project_name': 'Spectral Bandwidth Extension', 'entity': None, 'mode': 'online', 'log': 'all', 'log_freq': 5, 'n_files_to_log': 10, 'n_files_to_log_to_table': 10, 'tags': [], 'resume': False}, 'optim': 'adam', 'lr': 0.0003, 'beta1': 0.8, 'beta2': 0.999, 'losses': ['stft'], 'stft_sc_factor': 0.5, 'stft_mag_factor': 0.5, 'epochs': 125, 'ddp': False, 'ddp_backend': 'nccl', 'rendezvous_file': './rendezvous', 'rank': None, 'world_size': None, 'filename': '/content/test_16k_1.wav', 'output': '/content/outputs/'}
[2023-10-19 20:51:48,280][__main__][INFO] - Loading model aero from last state.
[2023-10-19 20:51:50,595][__main__][INFO] - lr wav shape: torch.Size([1, 117824])
[2023-10-19 20:51:50,595][__main__][INFO] - number of chunks: 1
Error executing job with overrides: ['dset=16-48', 'experiment=aero_4-16_512_64', '+filename=/content/test_16k_1.wav', '+output=/content/outputs/']
Traceback (most recent call last):
  File "/content/aero/predict.py", line 77, in main
    pr_chunk = model(lr_chunk.unsqueeze(0).to(device)).squeeze(0)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/aero/src/models/aero.py", line 472, in forward
    x = encode(x, inject)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/aero/src/models/aero.py", line 129, in forward
    x = self.dconv(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/aero/src/models/modules.py", line 241, in forward
    x = layer['time_attn'](x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/aero/src/models/modules.py", line 117, in forward
    dots += torch.einsum("fts,bhfs->bhts", decay_kernel, decay_q)
  File "/usr/local/lib/python3.10/dist-packages/torch/functional.py", line 360, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: CUDA out of memory. Tried to allocate 6.47 GiB (GPU 0; 14.75 GiB total capacity; 7.77 GiB already allocated; 5.53 GiB free; 8.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trac
```

**Comment by youssefabdelm** [comment]
Okay after dropping it to 3 seconds it finally worked. Any idea how I can increase that?

Edit: aaand I'm getting silence like you guys said haha

**Comment by fmac2000** [comment]
> Okay after dropping it to 3 seconds it finally worked. Any idea how I can increase that?
> 
> Edit: aaand I'm getting silence like you guys said haha

So you’re experiencing an OOM error, in predict.py you can change the SEGMENT_DURATION_SEC var to something lower, maybe 3 in your case.

With regard to the silence error, it’s due to the 16-48k model being overfit - if you use mandel’s models it should work. 12-48khz

**Comment by tshmak** [comment]
I'm also experiencing this issue. I'm applying Aero to a bunch of non-English data, and most of my wavfiles had this issue. Appreciate your effort into sharing your trained model. I know this is not going to be easy, but it would be better if we could identify the root cause of this in the model.

**Comment by tshmak** [comment]
Actually, I found that this problem affects the 12-48_512_128 checkpoint as well. So the model itself is buggy.

**Comment by fmac2000** [comment]
> Actually, I found that this problem affects the 12-48_512_128 checkpoint as well. So the model itself is buggy.

Hi,
I don’t think this model is in anyway buggy, only that it doesn’t generalise to out of domain samples very well - and should probably be evaluated on (same lang) out of domain sources through training. I’m not entirely sure.

I won’t be retraining this model in the future for general purpose, if I do, it’d likely be for single speaker internal research. I suppose it wouldn’t cost too much to train this yourself - depending on the hyperparams.

Sorry to disappoint but thanks to the author for publishing this repo and the model weights as opensource- it still holds up as SOTA 🎸

**Comment by tshmak** [comment]
I don't want to sound unappreciative of you or the author for sharing your codes and the models to us *for free* and with a permissive license. I do agree that it does sound good in the case where it works. However, I think it is right to call it a bug, unless the author's intent is that the model is for demo purposes only. It is unclear what exactly qualifies as "out-of-domain" and at the moment it cannot be used in any serious pipelines or products where we have no control over the input audios. But, just to be clear -- no complaints here! It is kind enough to share the codes.

**Comment by fmac2000** [comment]
I’d try training it on a larger and more diverse dataset and see if the “bug” is fixed. If you believe it to be a bug with the model, try using a LM trained solely on English to output Chinese and see if that lm is bugged as well.

**Comment by tshmak** [comment]
I'm sorry if I was not clear. In fact the problem did not just affect Chinese input. It affected English input as well.
