### ISSUE TITLE
Optimal configuration for 12khz - 48khz

### ISSUE THREAD

**Issue by fmac2000** [slp-rl/aero#5]
Hi Authors,

Are there any specific alterations to the configuration for 12->48khz upsample?
I seem to be generating a spectrogram with a distinct cut such as the one seen in Fig3 (before spectral upsampling) on longer voice clips

Thanks, appreciate the work

![GQu4hZZ](https://user-images.githubusercontent.com/62116993/221447990-527b7b0f-ce12-464c-a8e4-29d4796a9824.jpg)

**Comment by m-mandel** [comment]
Hey,
No alterations were customized for the 12-48 setting, that seem to cause this.
As noted in the paper, due to reserving computational resources, the number of frequencies parameter was chosen to be 1024 - so that the input to the model would be smaller.

No idea what would cause this. I notice that you used Mel-Spectrogram to display the signal, not that I think it matters.

**Comment by Ma5onic** [comment]
@m-mandel, could you please add some examples on how to train and test/predict on the musdb18-hq dataset?
I think there are some missing config files.

**Comment by Ma5onic** [comment]
https://github.com/Ma5onic/aero/blob/main/AeroDebug.ipynb

**Comment by Ma5onic** [comment]
@m-mandel, do you have the dataprep scripts for musdb? what file structure should I have for the current scripts to work?

**Comment by m-mandel** [comment]
Hi,
I resampled the musdb from 44.1 kHz to 11.025 kHz (a factor of 4), and created the appropriate egs files. Then added the paths of the relevant egs files to a dset conf file:

```
# @package dset
name: musdb-mixture-11-44
train: egs/musdb18hq/11025-44100_mixture/tr
valid: egs/musdb18hq/11025-44100_mixture/val
test: egs/musdb18hq/11025-44100_mixture/val

```

Then, I ran the model using these arguments:

```
python train.py \
  dset=musdb-mixture-11-44 \
  experiment=<experiment_name> \
  experiment.nfft=512 \
  experiment.hop_length=64 \
  experiment.lr_sr=11025 \
  experiment.hr_sr=44100 \
  epochs=696 \
  eval_every=175 \
  losses=[stft] \
  experiment.batch_size=16 \
  cross_valid_every=5 \
  wandb.resume=false \
  experiment.aero.spec_upsample=true \
  experiment.upsample=false \
  experiment.aero.enc_freq_attn=0 \
  experiment.aero.norm_starts=2 \
  experiment.aero.dconv_time_attn=2 \
  experiment.aero.dconv_lstm=2 \
  experiment.aero.freq_ends=4 \
  experiment.aero.strides=[4,4,2,2] \
  experiment.aero.channels=48 \
  experiment.melgan_discriminator.ndf=16 \
  +experiment.speech_mode=false \
  cross_valid=false \
  joint_evaluate_and_enhance=true \
  ddp=true \
  visqol=false \
```

Hope this helps.

**Comment by Ma5onic** [comment]
> Hi, I resampled the musdb from 44.1 kHz to 11.025 kHz (a factor of 4), and created the appropriate egs files. Then added the paths of the relevant egs files to a dset conf file:
> 
> ```yaml
> # @package dset
> name: musdb-mixture-11-44
> train: egs/musdb18hq/11025-44100_mixture/tr
> valid: egs/musdb18hq/11025-44100_mixture/val
> test: egs/musdb18hq/11025-44100_mixture/val
> ```
> 
> Then, I ran the model using these arguments:
> 
> ```bash
> python train.py \
>   dset=musdb-mixture-11-44 \
>   experiment=<experiment_name> \
>   experiment.nfft=512 \
>   experiment.hop_length=64 \
>   experiment.lr_sr=11025 \
>   experiment.hr_sr=44100 \
>   epochs=696 \
>   eval_every=175 \
>   losses=[stft] \
>   experiment.batch_size=16 \
>   cross_valid_every=5 \
>   wandb.resume=false \
>   experiment.hdemucs.spec_upsample=true \
>   experiment.upsample=false \
>   experiment.hdemucs.enc_freq_attn=0 \
>   experiment.hdemucs.norm_starts=2 \
>   experiment.hdemucs.dconv_time_attn=2 \
>   experiment.hdemucs.dconv_lstm=2 \
>   experiment.hdemucs.freq_ends=4 \
>   experiment.hdemucs.strides=[4,4,2,2] \
>   experiment.hdemucs.channels=48 \
>   experiment.melgan_discriminator.ndf=16 \
>   +experiment.speech_mode=false \
>   cross_valid=false \
>   joint_evaluate_and_enhance=true \
>   ddp=true \
>   visqol=false \
> ```
> 
> Hope this helps.

Could you please upload your experiment yaml? I get errors when trying it this way.
```
Traceback (most recent call last):
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/train.py", line 135, in main
    _main(args)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/train.py", line 127, in _main
    run(args)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/train.py", line 39, in run
    models = modelFactory.get_model(args)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/src/models/modelFactory.py", line 8, in get_model
    generator = Aero(**args.experiment.aero)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 373, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 818, in format_and_raise
    _raise(ex, cause)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 367, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    return self._resolve_with_default(
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 65, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 616, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 482, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 911, in accept
    return visitor.visitInterpolationNode(self)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 643, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/media/ML-Dev/AI-Disk/code/audio/enhancement/aero/venv/lib/python3.9/site-packages/omegaconf/base.py", line 573, in _resolve_node_interpolation
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'nfft' not found
    full_key: experiment.aero.nfft
    object_type=dict
```


I also had to add a couple `+` to the command options solve `Could not override 'experiment.hdemucs.blah'` errors:
```bash
python train.py \
  dset=musdb18-sep \
  experiment=musdb18-sep \
  experiment.nfft=512 \
  experiment.hop_length=256 \
  experiment.lr_sr=44100 \
  experiment.hr_sr=44100 \
  epochs=696 \
  eval_every=175 \
  losses=[stft] \
  experiment.batch_size=16 \
  cross_valid_every=5 \
  wandb.resume=false \
  +experiment.hdemucs.spec_upsample=true \
  experiment.upsample=false \
  +experiment.hdemucs.enc_freq_attn=0 \
  +experiment.hdemucs.norm_starts=2 \
  +experiment.hdemucs.dconv_time_attn=2 \
  +experiment.hdemucs.dconv_lstm=2 \
  +experiment.hdemucs.freq_ends=4 \
  +experiment.hdemucs.strides=[4,4,2,2] \
  +experiment.hdemucs.channels=48 \
  experiment.melgan_discriminator.ndf=16 \
  +experiment.speech_mode=false \
  cross_valid=false \
  joint_evaluate_and_enhance=true \
  ddp=true \
  visqol=false
```

**Comment by Ma5onic** [comment]
Thank you very much @m-mandel. 
I do have a couple follow up questions, if you don't mind:
What does `<experiment_name>` represent? is the file name of a yaml expertiment config that is being overwritten, or is it the desired value for `experiment.name`?

---

Also, what should the dataset file/folder structure when training on musdb18hq?
Would you describe it as `Type 1`, `Type 2` or is it something different?:
* **Type 1 (MUSDB)**: different folders. Each folder contains all needed stems in format `InstrumentName.wav`. The same as in MUSDBHQ18 dataset.
```
./egs/musdb18hq/11025-44100_mixture/val/
--- Song1/:
------ vocals.wav  
------ bass.wav 
------ drums.wav
------ other.wav
------ mixture.wav
--- Song2/:
------ vocals.wav  
------ bass.wav 
------ drums.wav
------ other.wav
------ mixture.wav
--- Song3/:
...........
```

* **Type 2 (Stems)**: each folder is "stem name". Folder contains wav files which consists only of required stem.
```
./egs/musdb18hq/11025-44100_mixture/val/
--- vocals/:
------ vocals_Song1.wav
------ vocals_Song2.wav
------ vocals_Song3.wav
------ vocals_Song4.wav
------ ...
--- bass/:
------ bass_Song1.wav
------ bass_Song2.wav
------ bass_Song3.wav
------ bass_Song4.wav
------ ...
...........
```
From what I can recall from my attempt, I got stuck when trying to create the metadata files with `create_meta_files.py` because it didn't support my dataset structures & it wasn't clear how you did your did your training/validation/test split on the musdb18hq dataset.

Great work on the paper/code & thank you in advance! I look forward to training some AERO models 😄
